# Generated by Django 4.1.3 on 2022-12-07 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
