# Generated by Django 4.1.3 on 2022-12-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_user_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='social',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
