# Generated by Django 4.1.3 on 2022-12-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_user_subscribe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_publish',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('active', 'Faol'), ('cancel', 'Bekor qilindi'), ('pending', 'Kutilmoqda')], default='pending', max_length=20),
        ),
    ]
